color_scheme: "dark"
heading_anchors: true
logo: "/assets/images/logo-mbari-3b.png"
remote_theme: pmarsceill/just-the-docs
search_enabled: true
search_tokenizer_separator: /[\s/]+/
title: vars-kb-server

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true